from chimerax.core.commands import run
run(session, 'open 1BJF')
run(session, 'show c')
run(session, 'show a')
run(session, 'show s')
run(session, 'cartoon style modeHelix tube sides 20')
run(session, 'style stick')
run(session, 'color sequential palette Purples-9')
run(session, 'transparency 90 s')
run(session, 'color byhetero')
run(session, 'sequence chain all')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')