from chimerax.core.commands import run
run(session, 'open 1EC6')
run(session, 'show c')
run(session, 'show a')
run(session, 'hide s')
run(session, 'transparency 80 atoms')
run(session, 'cartoon style coil xsection oval')
run(session, 'cartoon style xsection barbell modeHelix default')
run(session, 'nucleotides ladder')
run(session, 'color bychain')
run(session, 'lighting flat')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')