from chimerax.core.commands import run
run(session, 'open 1QKY')
run(session, 'show c')
run(session, 'show a')
run(session, 'show s')
run(session, 'color sequential palette Reds-5')
run(session, 'cartoon style coil xsection oval')
run(session, 'cartoon style xsection barbell modeHelix default')
run(session, 'style stick')
run(session, 'hbonds reveal true')
run(session, 'transparency 90 s')
run(session, 'sequence chain all')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')