from chimerax.core.commands import run
run(session, 'open 1VYC')
run(session, 'show c')
run(session, 'show a')
run(session, 'show s')
run(session, 'style stick')
run(session, 'color sequential palette PuBu')
run(session, 'hbonds reveal true')
run(session, 'transparency 90 s')
run(session, 'sequence chain all')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')