from chimerax.core.commands import run
run(session, 'open 4XIX')
run(session, 'show a')
run(session, 'show c')
run(session, 'hide s')
run(session, 'style ball')
run(session, 'color bychain')
run(session, 'transparency 35 atoms')
run(session, 'cartoon style coil xsection oval')
run(session, 'cartoon style xsection barbell modeHelix default')
run(session, 'sequence chain /A /B /C /D /E /F /G /H')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')
