from chimerax.core.commands import run
run(session, 'open 6F25')
run(session, 'show c')
run(session, 'show a')
run(session, 'style stick')
run(session, 'color bychain')
run(session, 'cartoon style modeHelix tube sides 20')
run(session, 'show s')
run(session, 'transparency 90 s')
run(session, 'sequence chain all')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')