from chimerax.core.commands import run
run(session, 'open 7XCE')
run(session, 'show c')
run(session, 'show a')
run(session, 'show s')
run(session, 'cartoon style protein modeHelix default arrows false xsection oval width 1.5 thickness 1.5')
run(session, 'style ball')
run(session, 'size ballscale 0.175')
run(session, 'color sequential palette Reds-5')
run(session, 'transparency 90 s')
run(session, 'sequence chain all')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')
