from chimerax.core.commands import run
run(session, 'open 8GRZ')
run(session, 'show c')
run(session, 'show a')
run(session, 'style ball')
run(session, 'size ballScale 0.175')
run(session, 'cartoon style modeHelix tube sides 20')
run(session, 'color sequential palette Purples-9')
run(session, 'show s')
run(session, 'transparency 90 s')
run(session, 'sequence chain all')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')