from chimerax.core.commands import run
run(session, 'open 8UB2')
run(session, 'show c')
run(session, 'show a')
run(session, 'hide s')
run(session, '~hbonds')
run(session, 'color bychain')
run(session, 'cartoon style coil xsection oval')
run(session, 'cartoon style xsection barbell modeHelix default')
run(session, 'transparency 60 atoms')
run(session, 'sequence chain all')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')