from chimerax.core.commands import run
run(session, 'open 8VB4')
run(session, 'show c')
run(session, 'show a')
run(session, 'hide s')
run(session, 'style sphere')
run(session, 'color sequential palette Purples-9')
run(session, 'transparency 65 atoms')
run(session, 'car style  protein modeh default arrows f xsect oval width 1 thick 1')
run(session, 'sequence chain all')
run(session, 'view orient')
run(session, 'ui tool show "Side View"')
run(session, 'graphics silhouettes true')
run(session, 'set bgColor #ffffff00')